- Aggregating_Option/process.yml
Updates to the process data source.
> Updates from ADS - Process

- Aggregating_Option/traffic.yml
> New Data Source from ADS - Traffic

- Aggregating_Option/network_accounting.yml
Logging of activity on networking devices
> Adding network device accounting

- Aggregating_Option/firewall.yml
> New Data Source from ADS - Firewall

- Aggregating_Option/windows_active_directory.yml
Updates to the active directory data source.
> Updates from ADS - Active Directory

- Aggregating_Option/wmi_object.yml
Updates to the WMI data source.
> Updates from ADS - WMI

- Aggregating_Option/module.yml
Updates to the module data source.
> Updates from ADS - Module

- Aggregating_Option/service.yml
Updates to the service data source.
> Updates from ADS - Service

- Aggregating_Option/file.yml
Updates to the file data source.
> Updates from ADS - File

- Aggregating_Option/cloud_service.yml
- Aggregating_Option/cloud_storage.yml
Added the following:
- Cloud Service: Cloud Service Disable
- Cloud Storage: Cloud Storage Modification
Added "bucket" as word to describe buckets/containers/folders in blob storage.
> Updates to cloud service/storage

- Aggregating_Option/driver.yml
> New Data Source from ADS - Driver

- Aggregating_Option/network_share.yml
New network share data source.
> New Data Source from ADS - Network Share

- Aggregating_Option/firmware.yml
> New Data Source from ADS - Firmware

- Aggregating_Option/named_pipe.yml
Updates to the named pipe data source.
> Updates from ADS - Named Pipe

- Aggregating_Option/kernel.yml
> New Data Source from ADS - Kernel

- Aggregating_Option/powershell_log.yml
- Aggregating_Option/script.yml
Updates to the powershell log data source.
> Updates from ADS - Powershell

- contribution/cluster.yml
- contribution/command.yml
- contribution/container.yml
- contribution/instance.yml
- contribution/pod.yml
- contribution/scheduled_job.yml
- contribution/user_account.yml
Added new containers data sources:
- Container
- Pod
- Cluster
Added containers as platform/collection layer to applicable existing data sources:
- Command
- Scheduled Job
- User Account
Fix typo in Instance data source while we're at it.
> Containers updates

- contribution/image.yml
While processing the YAML files using Python I noticed it has an invalid indentation at line 32.
> Fix for an invalid indentation

- contribution/application_log.yml
- contribution/cloud_service.yml
- contribution/firewall.yml
- contribution/group.yml
- contribution/logon_session.yml
- contribution/user_account.yml
- contribution/web_credential.yml
Adds Google Workspace platform to the following data sources:
- Application Log
- Cloud Service
- Firewall
- Group
- Logon Session
- User Account
- Web Credential
> Add google workspace platform

- attack_data_sources.yaml
- contribution/command.yml
- contribution/windows_registry.yml
Standardized case for a few data points since writing everything case insensitive started to get a bit cumbersome.
> Standardized case for a few data points

- contribution/active_directory.yml
- contribution/cloud_service.yml
- contribution/cloud_storage.yml
- contribution/cluster.yml
- contribution/command.yml
- contribution/container.yml
- contribution/drive.yml
- contribution/driver.yml
- contribution/file.yml
- contribution/firewall.yml
- contribution/firmware.yml
- contribution/group.yml
- contribution/image.yml
- contribution/kernel.yml
- contribution/logon_session.yml
- contribution/module.yml
- contribution/named_pipe.yml
- contribution/network_share.yml
- contribution/network_traffic.yml
- contribution/pod.yml
- contribution/process.yml
- contribution/scheduled_job.yml
- contribution/script.yml
- contribution/sensor_health.yml
- contribution/service.yml
- contribution/snapshot.yml
- contribution/user_account.yml
- contribution/volume.yml
- contribution/wmi_object.yml
PR to update CTID contributor name to Center for Threat-Informed Defense on all .yml files.
> Updating CTID contributor name

- contribution-ics/assets.yml
- contribution-ics/operational_databases.yml
PR to fix data components structure in ICS folder.
> Fixing data components structure for ICS
